### ISSUE TITLE
TODO Topics

### ISSUE THREAD

**Issue by prateekiiest** [vorburger/opendaylight-bot#10]
https://github.com/vorburger/opendaylight-bot/blob/90166cb7364e497bb9a34d7d54704e496ef1fb10/bot/src/main/java/org/opendaylight/bot/Bot.java#L71

Will this contain a list of things under a particular topic as mentioned by the string topic?

**Comment by vorburger** [comment]
@prateekiiest yes, but things move fast and this is no longer needed already (because we now have a Python script on Jenkins which can do the equivalent). The focus now is on JIRA & Jenkins automation and integration. Close this issue?

**Comment by prateekiiest** [comment]
ok, I am closing this
